import { SYMBOL_UNIVERSE, SYMBOL_MAP, SECTORS, NIFTY50_SYMBOL, type Sector } from "../symbols.js";
import { MockProvider, stepMarket, allSimSymbols, fastForwardMarket, resetToBootSnapshot, BOOT_TS } from "./mockProvider.js";
import type { MarketDataProvider, Quote } from "./provider.js";
import { recordShockEvents, recordTimedShockEvents, deleteEventsSince } from "../events.js";

const ALL_SYMBOLS = allSimSymbols();
const TICK_MS = 4000;
const HISTORY_POINTS = 180; // ~12 minutes of ticks at 4s, enough for an intraday sparkline/chart
const STALE_AFTER_MS = 20_000;

// Real Indian market data (NSE) is not free/keyless the way US equities are
// via Finnhub, so this app runs entirely on MockProvider. The interface
// still exists so a real vendor (Kite Connect, Upstox, NSE's own feed)
// could be dropped in later without touching any caller.
const mock: MarketDataProvider = new MockProvider();

interface LiveEntry {
  quote: Quote;
  history: { ts: number; price: number }[];
  updatedAt: number;
}

const live = new Map<string, LiveEntry>();
let lastTickAt = 0;

/** Pulls current provider state into the `live` cache (quote + history + freshness). Shared by the regular tick loop and the time-travel fast-forward. */
async function syncLiveFromState(): Promise<void> {
  const quotes = await mock.getQuotes(ALL_SYMBOLS);
  const now = Date.now();
  for (const symbol of ALL_SYMBOLS) {
    const chosen = quotes.get(symbol);
    if (!chosen) continue;
    const prev = live.get(symbol);
    const history = prev?.history ?? [];
    history.push({ ts: now, price: chosen.price });
    while (history.length > HISTORY_POINTS) history.shift();
    live.set(symbol, { quote: chosen, history, updatedAt: now });
  }
  lastTickAt = now;
}

async function tick(): Promise<void> {
  const shocks = stepMarket();
  if (shocks.length > 0) await recordShockEvents(shocks);
  await syncLiveFromState();
}

let started = false;
export function startMarketEngine(): void {
  if (started) return;
  started = true;
  void tick();
  setInterval(() => {
    void tick();
  }, TICK_MS);
}

/**
 * Time-travel demo control: compresses `hours` of simulated market movement
 * into one call. User watchlist baselines are untouched — only the shared
 * market state advances — so calling this and then reloading the dashboard
 * reproduces exactly what "coming back after being away" looks like,
 * without needing to actually wait.
 */
export async function fastForwardHours(hours: number): Promise<{ shockCount: number; hours: number }> {
  const shocks = fastForwardMarket(hours);
  if (shocks.length > 0) await recordTimedShockEvents(shocks);
  await syncLiveFromState();
  return { shockCount: shocks.length, hours };
}

/**
 * Undoes every simulated fast-forward and returns the market to exactly
 * how it looked at server boot — so trying "+4h", deciding you'd rather
 * see "+8h" instead, means resetting to a known baseline first rather than
 * the two runs silently stacking into an inaccurate 12h. Also clears the
 * intraday chart history (otherwise the 1D sparkline would show a fake
 * cliff jumping from the simulated price back to the reset price) and
 * deletes any events generated by simulation since boot, leaving the
 * original seeded historical events untouched.
 */
export async function resetSimulation(): Promise<void> {
  resetToBootSnapshot();
  for (const entry of live.values()) entry.history = [];
  await deleteEventsSince(BOOT_TS);
  await syncLiveFromState();
}

export interface EnrichedQuote extends Quote {
  history: number[];
  isStale: boolean;
  degraded: boolean;
  ageMs: number;
}

export function getQuote(symbol: string): EnrichedQuote | null {
  const entry = live.get(symbol);
  if (!entry) return null;
  const ageMs = Date.now() - entry.updatedAt;
  return {
    ...entry.quote,
    history: entry.history.map((h) => h.price),
    isStale: ageMs > STALE_AFTER_MS,
    degraded: false,
    ageMs,
  };
}

export function getQuotes(symbols: string[]): Map<string, EnrichedQuote> {
  const out = new Map<string, EnrichedQuote>();
  for (const symbol of symbols) {
    const q = getQuote(symbol);
    if (q) out.set(symbol, q);
  }
  return out;
}

export function getEngineHealth() {
  return {
    provider: "mock",
    lastTickAt,
    trackedSymbols: live.size,
  };
}

export function listAllSymbolsWithQuotes(): EnrichedQuote[] {
  return SYMBOL_UNIVERSE.map((s) => getQuote(s.symbol)).filter((q): q is EnrichedQuote => q !== null);
}

/**
 * Sector index level: an equal-weighted average of "return since inception"
 * across that sector's constituents, rebased to 1000. Computed on demand
 * from live quotes rather than simulated separately, so it's always
 * consistent with the underlying stock prices driving it.
 */
export function getSectorIndex(sector: Sector): { level: number; pctChange: number } | null {
  const members = SYMBOL_UNIVERSE.filter((s) => s.sector === sector);
  if (members.length === 0) return null;
  let sumReturn = 0;
  let sumDayReturn = 0;
  let count = 0;
  for (const m of members) {
    const q = getQuote(m.symbol);
    if (!q) continue;
    sumReturn += q.price / m.basePrice - 1;
    sumDayReturn += q.prevClose > 0 ? q.price / q.prevClose - 1 : 0;
    count++;
  }
  if (count === 0) return null;
  return {
    level: Math.round(1000 * (1 + sumReturn / count) * 100) / 100,
    pctChange: Math.round((sumDayReturn / count) * 10000) / 10000,
  };
}

export function getAllSectorIndices(): Record<Sector, { level: number; pctChange: number }> {
  const out = {} as Record<Sector, { level: number; pctChange: number }>;
  for (const sector of SECTORS) {
    const idx = getSectorIndex(sector);
    if (idx) out[sector] = idx;
  }
  return out;
}

export function getNiftyQuote(): EnrichedQuote | null {
  return getQuote(NIFTY50_SYMBOL);
}

export { SYMBOL_MAP };
